AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - "config/**/*"
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - "Gemfile"
  
Metrics/LineLength:
  Max: 130

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false