AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
  
Metrics/LineLength:
  Max: 130

Metrics/AbcSize:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 8

Metrics/BlockLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

GuardClause:
  MinBodyLength: 4

IfUnlessModifier:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false