FROM ruby:3.0.1-buster

WORKDIR /mysterysearch

RUN apt-get update \
  && apt-get install \
    openssl \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
  && wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && wget https://dev.mysql.com/get/mysql-apt-config_0.8.16-1_all.deb \
  && DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.16-1_all.deb \
  && apt-get update \
  && apt-get remove -y \
    libmariadbclient18 \
    libmariadbclient-dev-compat \
    libmariadbclient-dev \
  && apt-get install -y --allow-unauthenticated  \                                                                                        
    default-libmysqlclient-dev \
    mariadb-client \
    libxml2-dev \
    libxslt-dev \
    libc6-dev \
    nodejs \
    yarn \
    zip \
    vim \
  && gem install foreman \
  && apt-get clean \

RUN mkdir /mysterysearch
WORKDIR /mysterysearch

COPY Gemfile /mysterysearch/Gemfile
COPY Gemfile.lock /mysterysearch/Gemfile.lock

RUN bundle install
