version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  public_spree:
  storage:

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mysterysearch:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
      - chrome
    networks:
      - default
    volumes:
      - .:/mysterysearch
      - /mysterysearch/log
      - /mysterysearch/tmp
      - vendor_bundle:/mysterysearch/vendor/bundle
      - node_modules:/mysterysearch/node_modules
      - public_spree:/mysterysearch/public/spree
      - storage:/mysterysearch/storage
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - '4444:4444'
