version: 2.1 
orbs:
  ruby: circleci/ruby@0.1.2

jobs: 
  rspec: 
    working_directory: ~/mysterysearch 
    docker: 
      - image: circleci/ruby:3.0.1-node-browsers
      - image: circleci/mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          RAILS_ENV: test
          MYSQL_HOST: 172.21.0.2
    steps: 
      - checkout 
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run:
          name: Bundler install
          command: |
            gem update --system
            gem install bundler
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Yarn install
          command: yarn install --cache-folder ~/.cache/yarn
      - run:
          name: Database setup
          command: bin/rails db:create db:schema:load --trace
      - run: bundle exec bin/webpack
      - run:
          name: Run rubocop
          command: bundle exec rspec
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  rubocop:
    working_directory: ~/mysterysearch
    docker:
      - image: circleci/ruby:3.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  
  aws-ec2-deploy:
    working_directory: ~/mysterysearch
    docker:
      - image: circleci/ruby:3.0.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - 25:95:5a:a6:fd:88:d7:d0:59:b3:9b:09:18:ca:1e:fe
      - run: ssh -p 22 ec2-user@ec2-54-64-115-38.ap-northeast-1.compute.amazonaws.com "/home/ec2-user/nazonavi/deploy-me.sh"

workflows: 
  version: 2.1 
  test-and-deploy: 
    jobs: 
      - rspec 
      - rubocop 
      - aws-ec2-deploy:
          requires:
            - rspec
            - rubocop