version: '2.1'
jobs:
  rspec:
    working_directory: ~/mysterysearch
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run:
          name: Start containers and verify it is working
          command: |
            set -x
            docker-compose up -d
            docker exec mysterysearch curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000
      - run:
          name: Setup database
          command: |
            docker-compose exec mysterysearch bash -c 'yes n | bundle exec rails g spree:install --migrate --seed --sample --auto_accept'
      - run:
          name: Run rspec
          command: docker-compose exec mysterysearch rspec

  rubocop:
    working_directory: ~/mysterysearch
    docker:
      - image: circleci/ruby:2.7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

orbs:
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
  build-tools: circleci/build-tools@2.9.1
  jq: circleci/jq@1.9.1
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: MysterySearch
          bundle-bucket: mysterysearch
          bundle-key: <%= ENV["AWS_ACCESS_KEY"] %>
