version: 2.1 
orbs: 
  aws-ecr: circleci/aws-ecr@7.2.0 
  aws-ecs: circleci/aws-ecs@2.2.1 

jobs: 
  rspec: 
    working_directory: ~/mysterysearch 
    docker: 
      - image: circleci/ruby 
    steps: 
      - checkout 
      - setup_remote_docker 
      - run: 
          name: Setup environment variable 
          command: | 
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV 
      - run: 
          name: Start containers and verify it is working 
          command: | 
            set -x 
            docker-compose up -d 
            docker exec mysterysearch curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000 
      - run: 
          name: Run rspec 
          command: docker-compose exec mysterysearch rspec 

  rubocop: 
    working_directory: ~/mysterysearch 
    docker: 
      - image: circleci/ruby:3.0.1-node-browsers
    steps: 
      - checkout 
      - restore_cache: 
          keys: 
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }} 
            - gemfiles-{{ .Branch }}- 
      - run: bundle config --local path vendor/bundle 
      - run: 
          name: bundle install 
          command: bundle check || bundle config set --local clean 'true' 
      - save_cache: 
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }} 
          paths: 
            - vendor/bundle
      - run: 
          name: Run rubocop 
          command: docker-compose exec mysterysearch rubocop 

workflows: 
  version: 2.1 
  build-test-and-deploy: 
    jobs: 
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile.ci
          path: mysterysearch_mysterysearch_1
          profile-name: user1
          repo: ${MY_APP_PREFIX}
          tag: '${CIRCLE_SHA1}'
      - rspec 
      - rubocop 
      - aws-ecs/deploy-service-update:
          family: 'mysterysearch_app' 
          cluster-name: 'app' 
          container-image-name-updates: 'container=myapp,image-and-tag=${AWS_ECR_ACCOUNT_URL}/portfolio:${CIRCLE_SHA1}' 
          requires: 
            - rspec 
            - rubocop 
